
version: 0.2

#$CODEBUILD_SRC_DIR is is a given env var

env:
  variables:
    customenvkey: "mycustomenvvalue"
phases:
  install:
    commands:
      - echo "install command..."
  pre_build:
    commands:
      - echo "pre-build commands..."
  build:
    commands:
      - echo "build command..."
  post_build:
    commands:
      - cd src && zip -r ../package/src.zip * && cd ..
      - cp -r ./scaffolding/* ./package/
artifacts:
  files:
    - ./package/**/*
